### ISSUE TITLE
obtain the spot ID calculated by the juxta view

### ISSUE THREAD

**Issue by ckfromCN** [saezlab/mistyR#35]
Great work! I have two questions that might seem a bit silly. 

Regarding the two views, juxta and para, is the main difference that para decreases weights based on the inverse of the distance? For instance, when I set the radius to 5 for both  juxta and para view , will the furthest cell in the juxta view have the same impact as the one right next to it? Is my understanding correct?

Besides, I'm using your work with 10x Visium. When I specify the spot as intrinsic, is there a way to obtain the spot ID calculated by the juxta view?

**Comment by jtanevski** [comment]
The juxtaview considers information only from the immediate neighborhood. The neighborhood is determined by Delauney triangulation and the threshold parameter is just an additional filter that controls the maximum distance between two neighboring spots. The paraview is built using the whole slide, weighing each spot according to the distance from the spot of origin following one of several weighing functions and a parameter of that function. You can find more information about in the documentation for the function `add_paraview` 

The views you get by `add_juxtaview` and `add_paraview` are therefore going to be different and capture different spatial contexts. Note, also, that if you don't exclude the immediate neighborhood by defining a zone of indifference, i.e., a radius around the spot not to be considered when constructing the paraview, the paraview will also contain information from the immediate neighborhood with the highest weight. That means that depending on the chosen parameter of the weighting function the paraview can make the juxtaview redundant. 

Finally, since the Visium spots are ordered in a lattice the juxtaview for each spot will in the most general case contain information from its neighbors in locations +- 1 row and +- 1 column. if you want to play around and be really sure which spot IDs are taken into account you can use the package `deldir` to calculate the Delauney triangulation, given your spatial coordinates. This package and the function `deldir` is used in `add_juxtaview`.  See lines 274 -- 284 in R/view-composers.R for the exact implementation.

Hope this helps.
