### ISSUE TITLE
usage of mistyR for spatial transcriptome cell composition data 

### ISSUE THREAD

**Issue by archanabhardwaj** [saezlab/mistyR#36]
Hello 
Very useful tool. I would like to use it for my spatial transcriptome experiment. I have cell composition data from cell2location method which I would like to use ( "cell types" ) together with + pathways + TFs in this package. 

I can not find any tutorial explaning usage of cell2location data in misty. I also tried to follow link https://saezlab.github.io/mistyR/articles/mistySeurat.html but it does not work anymore. 

I would really appreciate your suggestions!! 

Thanks in advance

**Comment by jtanevski** [comment]
We are currently working on a new major version of mistyR with many new features as well as a number of vignettes for different use cases including working with c2l.

In the meantime, if it's not too late, here are some suggestions. Based on your description you would like to identify relationships between cell-types and pathways/tfs. Using c2l results here is straightforward and they can be used in several ways. 

A view composition oriented towards structural patterns using c2l data would start from an intraview where each spot is represented by the c2l estimates. It should be relatively easy to extract this information from any type of data format into a tibble or a data.frame. Since you are working with Visium data, the intraview already captures not only a single cell but a local spatial context. To this view you might consider adding a juxtaview or a paraview with a modest radius to capture a bit more of the tissue structure. Running MISTy with this view composition should already give you the most robust structural (cell-type to cell-type) patterns in two spatial contexts.

I understand that you might wish to explore a bit more the functional relationships around the available cell type. In this case you can start as before from the c2l results as intraview. To this view you can add 2 additional "intra"-views. One capturing the estimated pathway activities within the spot and a second capturing the tf activities within the spot. You can expand this composition by adding a corresponding pathway and tf  juxtaview or paraview. Now you have a view composition consisting of 5 views. When running `run_misty` don't forget to set  `bypass.intra = TRUE`. The results now give you a  variance explained per cell-type by two types of functional relationships coming from two spatial contexts. You can also learn how much each of the views contributed to the variance explained. Finally which pathways and tf coming from which context are most important for each cell-type. In a way, you get a functional deconvolution of pathway and tf activities per spot given the cell-types and in addition the related functional relationships in the broader tissue structure that can explain the abundance of each cell-type.

There can be, of course, many different combinations of the above that can help you answer the specific questions or hypotheses you have about your data. mistyR can support them quite flexibly. I hope this helped a bit. Also, feel free to reach out to me or to our lab in case you require more detailed support running our tools.
